
package com.example.webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BankAccountServiceImplService", targetNamespace = "http://impl.webservice.example.com/", wsdlLocation = "http://sprincxfwebservice-env.elasticbeanstalk.com/BankAccountService/BankAccountService?wsdl")
public class BankAccountServiceImplService
    extends Service
{

    private final static URL BANKACCOUNTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BANKACCOUNTSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName BANKACCOUNTSERVICEIMPLSERVICE_QNAME = new QName("http://impl.webservice.example.com/", "BankAccountServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sprincxfwebservice-env.elasticbeanstalk.com/BankAccountService/BankAccountService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKACCOUNTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        BANKACCOUNTSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public BankAccountServiceImplService() {
        super(__getWsdlLocation(), BANKACCOUNTSERVICEIMPLSERVICE_QNAME);
    }

    public BankAccountServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKACCOUNTSERVICEIMPLSERVICE_QNAME, features);
    }

    public BankAccountServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, BANKACCOUNTSERVICEIMPLSERVICE_QNAME);
    }

    public BankAccountServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKACCOUNTSERVICEIMPLSERVICE_QNAME, features);
    }

    public BankAccountServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankAccountServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IBankAccountService
     */
    @WebEndpoint(name = "BankAccountServiceImplPort")
    public IBankAccountService getBankAccountServiceImplPort() {
        return super.getPort(new QName("http://impl.webservice.example.com/", "BankAccountServiceImplPort"), IBankAccountService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBankAccountService
     */
    @WebEndpoint(name = "BankAccountServiceImplPort")
    public IBankAccountService getBankAccountServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.example.com/", "BankAccountServiceImplPort"), IBankAccountService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKACCOUNTSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw BANKACCOUNTSERVICEIMPLSERVICE_EXCEPTION;
        }
        return BANKACCOUNTSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
